<?php

namespace OpnsenseApiIntrospect\Emitter;

/**
 * Map the endpoint inventory to a minimal OpenAPI 3 document.
 *
 * Request vs response is driven by the action direction (read/write/command):
 * the OPNsense base controllers serialise the model node tree as the *response*
 * of read actions (getNodes(), where list fields become {key:{value,selected}}
 * maps) and consume a subset as the *request* of write actions. Heuristic verbs,
 * directions and best-effort bodies are flagged with `x-opnsense-*` extensions.
 */
final class OpenApiEmitter
{
    private const FIELD_TYPE_MAP = [
        'BooleanField' => 'string',   // serialised as "0"/"1"
        'IntegerField' => 'string',
        'PortField' => 'string',
        'NetworkField' => 'string',
    ];

    /**
     * @param array<int,array<string,mixed>> $endpoints
     */
    public function emit(array $endpoints, array $meta): string
    {
        $paths = [];
        foreach ($endpoints as $ep) {
            $path = $ep['path'];
            $multiVerb = count($ep['verbs']) > 1;
            foreach ($ep['verbs'] as $verb) {
                $opEp = $ep;
                if ($multiVerb && isset($opEp['operationId'])) {
                    $opEp['operationId'] = $opEp['operationId'] . '.' . strtoupper($verb);
                }
                $paths[$path][strtolower($verb)] = $this->operation($opEp);
            }
        }

        $doc = [
            'openapi' => '3.0.3',
            'info' => [
                'title' => 'OPNsense API (introspected)',
                'version' => (string)($meta['opnsense_version'] ?? 'unknown'),
                'description' => 'Generated by api-introspect via runtime reflection. '
                    . 'HTTP verbs and request/response directions are heuristic.',
            ],
            // Self-describing run metadata (counts, provenance distributions,
            // source checkout). Vendor extension, so the document stays valid.
            'x-opnsense-introspection' => $this->introspectionMeta($meta),
            'paths' => $paths,
        ];

        return json_encode($doc, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . "\n";
    }

    /**
     * Surface the run metadata that is otherwise dropped (only the version
     * reaches `info`). Carries the counts and the direction-source provenance
     * distribution so a consumer can tell how the document was produced and how
     * much of it is parsed-authoritative. The opnsense_root checkout path is
     * deliberately omitted — it is a sensitive local path, not spec content.
     *
     * @param array<string,mixed> $meta
     * @return array<string,mixed>
     */
    private function introspectionMeta(array $meta): array
    {
        $out = [
            'generator' => $meta['generator'] ?? 'api-introspect',
            'generated_at' => $meta['generated_at'] ?? null,
            'opnsense_version' => $meta['opnsense_version'] ?? null,
            'acl_privileges_indexed' => $meta['acl_privileges_indexed'] ?? null,
            'stats' => $meta['stats'] ?? null,
        ];
        return array_filter($out, static fn($v) => $v !== null);
    }

    private function operation(array $ep): array
    {
        $op = [
            'operationId' => $ep['operationId'] ?? null,
            'tags' => [$ep['module'] ?? 'misc'],
            'x-opnsense-controller' => $ep['controller'] ?? null,
            'x-opnsense-verb-heuristic' => $ep['verbs_heuristic'] ?? true,
            'x-opnsense-direction' => $ep['direction'] ?? 'unknown',
            // How `direction` was determined: `wrapper:<base method>` or
            // `literal` (parsed from the action body — authoritative), vs
            // `name-heuristic` (fell back to the method-name prefix).
            'x-opnsense-direction-source' => $ep['direction_source'] ?? 'name-heuristic',
        ];

        if (!empty($ep['privileges'])) {
            $op['x-opnsense-privilege'] = array_column($ep['privileges'], 'name');
        }

        $params = [];
        foreach ($ep['pathParams'] ?? [] as $p) {
            // OpenAPI requires `required: true` for every path parameter (the
            // placeholder is part of the URL template). When the underlying
            // action arg is optional there is a collection-level variant of the
            // route without this segment; that is flagged as an extension rather
            // than an (invalid) optional path parameter.
            $param = [
                'name' => $p['name'],
                'in' => 'path',
                'required' => true,
                'schema' => ['type' => 'string'],
            ];
            if ($p['optional'] ?? false) {
                $param['x-opnsense-optional'] = true;
            }
            $params[] = $param;
        }
        if ($params) {
            $op['parameters'] = $params;
        }

        [$requestBody, $responses] = $this->bodies($ep);
        if ($requestBody !== null) {
            $op['requestBody'] = $requestBody;
        }
        $op['responses'] = $responses;

        return array_filter($op, static fn($v) => $v !== null);
    }

    /**
     * Resolve the request body (or null) and the responses map for an endpoint.
     *
     * @return array{0:?array,1:array}
     */
    private function bodies(array $ep): array
    {
        $direction = $ep['direction'] ?? 'unknown';
        $model = $ep['model'] ?? null;
        $hasModel = is_array($model) && !empty($model['payload']);

        // Plain (non-model) controllers: only a best-effort request scan.
        if (!$hasModel) {
            $request = null;
            if (!empty($ep['bodyScan']['params'])) {
                $request = [
                    'x-opnsense-best-effort' => true,
                    'content' => ['application/x-www-form-urlencoded' => [
                        'schema' => [
                            'type' => 'object',
                            'properties' => array_fill_keys($ep['bodyScan']['params'], ['type' => 'string']),
                        ],
                    ]],
                ];
            }
            return [$request, $this->genericResponse($ep)];
        }

        $key = $model['payloadKey'] ?? $model['bodyKey'] ?? null;
        $fields = $model['payload'];

        // Soundness: only assert a field is required when the direction was
        // proven (a parsed base wrapper / inherited base action), i.e. we know
        // the request actually consumes the model body and the model enforces
        // requiredness. For name-heuristic endpoints the body is a best-effort
        // guess, so every field stays optional -- we never claim a field exists
        // unless we can prove it does.
        $provable = ($ep['direction_source'] ?? 'name-heuristic') !== 'name-heuristic';

        return match ($direction) {
            'read' => [null, $this->readResponse($ep, $key, $fields, $provable)],
            'write' => [
                $this->jsonBody($this->wrap($key, $this->objectSchema($fields, 'request', $provable), $provable)),
                $this->writeResponse($ep),
            ],
            'command' => [null, $this->statusResponse($ep)],
            default => [null, $this->genericResponse($ep)],
        };
    }

    /**
     * Read actions return the node tree (search/grid actions return a grid).
     *
     * When the shape is proven, the wrapper key is provably present: getBase /
     * getAction always wrap the payload under it (`{<key>: nodes}`), and
     * UIModelGrid::fetch always returns the full envelope. So those top-level
     * keys are marked required; for name-heuristic reads they stay optional.
     */
    private function readResponse(array $ep, ?string $key, array $fields, bool $provable): array
    {
        $isGrid = !empty($ep['grid']) || str_starts_with(lcfirst((string)($ep['action'] ?? '')), 'search');
        if ($isGrid) {
            $schema = [
                'type' => 'object',
                'properties' => [
                    'rows' => ['type' => 'array', 'items' => $this->searchRowSchema($fields)],
                    'rowCount' => ['type' => 'integer'],
                    'total' => ['type' => 'integer'],
                    'current' => ['type' => 'integer'],
                ],
            ];
            if ($provable) {
                $schema['required'] = ['rows', 'rowCount', 'total', 'current'];
            }
            return $this->okResponse($schema);
        }
        return $this->okResponse($this->wrap($key, $this->objectSchema($fields, 'response'), $provable));
    }

    /**
     * Grid rows (searchBase -> UIModelGrid::fetch) are flat scalars, not the
     * nested getNodes() tree: each leaf is `$field->getValue()` and option/
     * relation fields additionally emit a `%field` carrying the display label
     * (only when it differs from the raw value, so `%field` is not guaranteed).
     *
     * @param array<int,array<string,mixed>> $fields
     */
    private function searchRowSchema(array $fields): array
    {
        $props = ['uuid' => ['type' => 'string']];
        foreach ($this->flattenLeaves($fields) as $name => $field) {
            $props[$name] = ['type' => 'string'];
            // Fields with a selectable/option representation carry a label.
            if (($field['valueType'] ?? 'scalar') === 'map') {
                $props['%' . $name] = [
                    'type' => 'string',
                    'description' => "display label for \"{$name}\" "
                        . '(present when it differs from the raw value)',
                ];
            }
        }
        return ['type' => 'object', 'properties' => $props];
    }

    /**
     * Key the payload leaves by field name. The extractor already flattens
     * containers, so each entry is a scalar/list leaf or an array collection;
     * in a grid row a collection serialises to its raw value, i.e. one leaf.
     *
     * @param array<int,array<string,mixed>> $fields
     * @return array<string,array<string,mixed>>
     */
    private function flattenLeaves(array $fields): array
    {
        $out = [];
        foreach ($fields as $f) {
            $out[$f['name']] = $f;
        }
        return $out;
    }

    private function writeResponse(array $ep): array
    {
        // ApiMutableModelControllerBase::save() -> {"result":"saved"};
        // ::validate() -> {"result":"failed","validations":{field: msg|[msg,...]}}.
        $props = [
            'result' => ['type' => 'string', 'description' => '"saved" on success, "failed" on validation error'],
            'validations' => [
                'type' => 'object',
                'additionalProperties' => [
                    'oneOf' => [
                        ['type' => 'string'],
                        ['type' => 'array', 'items' => ['type' => 'string']],
                    ],
                ],
            ],
        ];
        // addBase() additionally returns the new node's uuid on success.
        if (str_starts_with(lcfirst((string)($ep['action'] ?? '')), 'add')) {
            $props['uuid'] = ['type' => 'string'];
        }
        return $this->okResponse(['type' => 'object', 'properties' => $props]);
    }

    private function statusResponse(array $ep): array
    {
        // delBase() -> {"result":"deleted"|"not found"|"failed"};
        // toggleBase() -> {"result":"Enabled"|"Disabled"|"failed","changed":bool}.
        $props = ['result' => ['type' => 'string']];
        if (str_starts_with(lcfirst((string)($ep['action'] ?? '')), 'toggle')) {
            $props['changed'] = ['type' => 'boolean'];
        }
        return $this->okResponse(['type' => 'object', 'properties' => $props]);
    }

    private function genericResponse(array $ep = []): array
    {
        // If the action returned a literal array, we at least know its top-level
        // keys (values untyped). Otherwise the shape is not statically derivable.
        if (!empty($ep['returnKeys'])) {
            $props = [];
            foreach ($ep['returnKeys'] as $k) {
                $props[$k] = ['description' => 'untyped (value type not statically known)'];
            }
            return $this->okResponse(
                ['type' => 'object', 'properties' => $props],
                'OK (keys parsed from return; value types unknown)'
            );
        }
        return $this->okResponse(['type' => 'object'], 'OK (response shape not statically derivable)');
    }

    private function okResponse(array $schema, string $desc = 'OK'): array
    {
        return ['200' => [
            'description' => $desc,
            'content' => ['application/json' => ['schema' => $schema]],
        ]];
    }

    /**
     * Wrap a field schema under the body key (e.g. {"rule": {...}}). When the
     * shape is proven the key itself is provably present (read response) or
     * mandatory (write request), so it is marked required; for a best-effort
     * body it stays optional.
     */
    private function wrap(?string $key, array $schema, bool $keyRequired = false): array
    {
        if ($key === null) {
            return $schema;
        }
        $obj = ['type' => 'object', 'properties' => [$key => $schema]];
        if ($keyRequired) {
            $obj['required'] = [$key];
        }
        return $obj;
    }

    private function jsonBody(array $schema): array
    {
        return ['content' => ['application/json' => ['schema' => $schema]]];
    }

    /**
     * Build an object JSON Schema from a (possibly nested) field list.
     *
     * $view selects the serialisation:
     *  - 'response': list fields render as option maps {key:{value,selected}}
     *    and array collections as {uuid: row} maps (matching getNodes()).
     *  - 'request': list fields render as submitted scalars (enum for single
     *    select; comma-separated string for multi-select) and array collections
     *    as arrays of row objects.
     *
     * $assertRequired gates the `required` list: only set it when the body is
     * proven (see bodies()), so a best-effort body never claims a field exists.
     *
     * @param array<int,array<string,mixed>> $fields
     */
    private function objectSchema(array $fields, string $view, bool $assertRequired = true): array
    {
        $props = [];
        $required = [];
        foreach ($fields as $f) {
            $name = $f['name'];

            if (!empty($f['array'])) {
                $row = $this->objectSchema($f['items'] ?? [], $view, $assertRequired);
                $props[$name] = $view === 'response'
                    ? ['type' => 'object', 'additionalProperties' => $row]   // {uuid: row}
                    : ['type' => 'array', 'items' => $row];
                continue;
            }

            $props[$name] = $this->leafSchema($f, $view);
            if ($view === 'request' && $assertRequired && !empty($f['required'])) {
                $required[] = $name;
            }
        }

        $obj = ['type' => 'object', 'properties' => $props];
        if ($required) {
            // Flattening sibling containers can surface two fields of the same
            // name (the `properties` map keeps one); keep `required` unique so it
            // satisfies the OpenAPI meta-schema (required has uniqueItems).
            $obj['required'] = array_values(array_unique($required));
        }
        return $obj;
    }

    /** @param array<string,mixed> $f */
    private function leafSchema(array $f, string $view): array
    {
        $isMap = ($f['valueType'] ?? 'scalar') === 'map';
        $options = $f['options'] ?? [];
        $multi = !empty($f['multiSelect']);

        if ($view === 'response') {
            if ($isMap) {
                // {optionKey: {value: label, selected: 0|1}}
                $schema = [
                    'type' => 'object',
                    'additionalProperties' => [
                        'type' => 'object',
                        'properties' => [
                            'value' => ['type' => 'string'],
                            'selected' => ['type' => 'integer', 'enum' => [0, 1]],
                        ],
                    ],
                ];
            } else {
                $schema = ['type' => self::FIELD_TYPE_MAP[$f['type']] ?? 'string'];
            }
        } else {
            // request view
            if ($isMap && $multi) {
                $schema = ['type' => 'string', 'description' => 'comma-separated selection'];
                if ($options) {
                    $schema['x-opnsense-options'] = $options;
                }
            } else {
                $schema = ['type' => self::FIELD_TYPE_MAP[$f['type']] ?? 'string'];
                if ($isMap && $options) {
                    $schema['enum'] = $options; // single-select
                }
            }
        }

        if (!empty($f['description'])) {
            $schema['description'] = ($schema['description'] ?? '') === ''
                ? $f['description']
                : $schema['description'];
        }
        return $schema;
    }
}
